### ISSUE TITLE
[Issue]: Reduced performance with MLIR running two models with default flags

### ISSUE THREAD

**Issue by causten** [ROCm/rocMLIR#1429] opened 2024-02-22 21:30 UTC
### Problem Description

While attempting to move the MLIR commit hash from bf2911e5 to da3df73b via https://github.com/ROCm/AMDMIGraphX/pull/2798 I saw a 13% drop in performance on 2 models.  

### Operating System

20.04.6

### CPU

AMD EPYC 7702 64-Core Processor

### GPU

AMD Instinct MI250, AMD Instinct MI100

### ROCm Version

ROCm 6.0.0

### ROCm Component

rocMLIR

### Steps to Reproduce

Using MLIR 
Before: bf2911e5245d6452d194ee5dc41c9c2b2869e5c0
After: da3df73b13c69d6b1d5ffec9c8281c261a0df257

migraphx-driver perf --gpu mobilenet_i64.pb

Before |  | After
-- | -- | -- 
gpu::code_object::mlir_convolution_add_clip:   7.59713ms / 26 = 0.292197ms |    | gpu::code_object::mlir_convolution_add_clip:   8.59946ms / 26 = 0.330749ms

migraphx-driver perf --gpu mobilenet_i64.pb

Before |  | After
-- | -- | -- 
gpu::code_object::mlir_convolution:   165.61ms / 237 = 0.698778ms |   | gpu::code_object::mlir_convolution:   184.571ms / 237 = 0.77878ms

**Comment by manupak** [comment] 2024-02-23 10:54
This is for 6.2... correct ? 

Additionally, we would need a detailed trace from the likes of https://github.com/ROCm/AMDMIGraphX/pull/2747.
Along with a MIGRAPHX_MLIR_TRACE=1 MIGRAPHX_TRACE_BENCHMARKING=2 for before and after.

We need the info tracked down to which kernel caused this. Ideally, we d like to see a bunch of kernels that caused the perf drop. The following is an example : 

```mlir
func.func @mlir_convolution(%arg0: !migraphx.shaped<1x2048x1x1xf32, 2048x1x1x1>, %arg1: !migraphx.shaped<1x2048x1x1xf32, 2048x1x1x1>, %arg2: !migraphx.shaped<1x2048x7x7xf32, 100352x49x7x1>, %arg3: !migraphx.shaped<1x2048x1x1xf32, 2048x1x1x1>, %arg4: !migraphx.shaped<1x1024x14x14xf32, 200704x196x14x1>, %arg5: !migraphx.shaped<2048x1024x1x1xf32, 1024x1x1x1>) -> !migraphx.shaped<1x2048x7x7xf32, 100352x49x7x1> {
    %0 = migraphx.multibroadcast %arg3 {out_dyn_dims = [], out_lens = [1, 2048, 7, 7]} : <1x2048x1x1xf32, 2048x1x1x1> -> <1x2048x7x7xf32, 0x1x0x0>
    %1 = migraphx.multibroadcast %arg1 {out_dyn_dims = [], out_lens = [1, 2048, 7, 7]} : <1x2048x1x1xf32, 2048x1x1x1> -> <1x2048x7x7xf32, 0x1x0x0>
    %2 = migraphx.multibroadcast %arg0 {out_dyn_dims = [], out_lens = [1, 2048, 7, 7]} : <1x2048x1x1xf32, 2048x1x1x1> -> <1x2048x7x7xf32, 0x1x0x0>
    %3 = migraphx.convolution %arg4, %arg5 {dilation = [1, 1], group = 1 : i64, padding = [0, 0, 0, 0], padding_mode = 0 : i64, stride = [2, 2]} : <1x1024x14x14xf32, 200704x196x14x1>, <2048x1024x1x1xf32, 1024x1x1x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    %4 = migraphx.mul %2, %3 : <1x2048x7x7xf32, 0x1x0x0>, <1x2048x7x7xf32, 100352x49x7x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    %5 = migraphx.mul %1, %4 : <1x2048x7x7xf32, 0x1x0x0>, <1x2048x7x7xf32, 100352x49x7x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    %6 = migraphx.mul %2, %arg2 : <1x2048x7x7xf32, 0x1x0x0>, <1x2048x7x7xf32, 100352x49x7x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    %7 = migraphx.mul %1, %6 : <1x2048x7x7xf32, 0x1x0x0>, <1x2048x7x7xf32, 100352x49x7x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    %8 = migraphx.add %7, %5 : <1x2048x7x7xf32, 100352x49x7x1>, <1x2048x7x7xf32, 100352x49x7x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    %9 = migraphx.add %8, %0 : <1x2048x7x7xf32, 100352x49x7x1>, <1x2048x7x7xf32, 0x1x0x0> -> <1x2048x7x7xf32, 100352x49x7x1>
    %10 = migraphx.relu %9 : <1x2048x7x7xf32, 100352x49x7x1> -> <1x2048x7x7xf32, 100352x49x7x1>
    return %10 : !migraphx.shaped<1x2048x7x7xf32, 100352x49x7x1>
  }
```

It is nearly impossible to do a bisect (thats a big jump on the commit pointer) on our tree to see which commit caused this without above information. Would you be able to provide this information ?

@jerryyin I dont think its good use of our time to do the above triage given the amount things we already have on our plates.
So I am assigning this back for the initial triage.

**Comment by manupak** [comment] 2024-02-23 11:04
Also there is not obvious issue we are seeing from average perf of conv on gfx90a : http://ml-ci-internal.amd.com:8080/job/MLIR/job/mlir-nightly-all/plot/#gfx90a_plot-nightly-perf-results-000001.csv

So definitely need more info.

**Comment by causten** [comment] 2024-02-24 19:21
[trace_da3df_mobilenet.gz](https://github.com/ROCm/rocMLIR/files/14394160/trace_da3df_mobilenet.gz)
[trace_da3df_nasnet.gz](https://github.com/ROCm/rocMLIR/files/14394164/trace_da3df_nasnet.gz)
[trace_bf2911_nasnet.gz](https://github.com/ROCm/rocMLIR/files/14394165/trace_bf2911_nasnet.gz)
[trace_bf2911_mobilenet.gz](https://github.com/ROCm/rocMLIR/files/14394166/trace_bf2911_mobilenet.gz)

**Comment by manupak** [comment] 2024-03-04 13:58
@causten did you use  MIGRAPHX_TRACE_BENCHMARKING=2 on those traces ? 
I cant see which solutions are being picked in the logs.

**Comment by manupak** [comment] 2024-03-04 15:11
So from your traces, I looked at the first four entries that has double-digit percentage out of the model run as follows : 

```
old:: gpu::code_object::mlir_convolution_add_clip<float_type(64x512x14x14:0x1x0x0, 64x512x14x14, 512x512x1x1, 64x512x14x14)>: 1.1345ms / 5 = 0.2269ms, 13%
    new:: gpu::code_object::mlir_convolution_add_clip<float_type(64x512x14x14:0x1x0x0, 64x512x14x14, 512x512x1x1, 64x512x14x14)>: 1.13616ms / 5 = 0.227232ms, 12%
old:: gpu::code_object::mlir_convolution_add_clip<float_type(64x512x14x14:0x1x0x0, 64x512x14x14, 512x1x3x3, 64x512x14x14)>: 1.12554ms / 5 = 0.225109ms, 13%
    new:: gpu::code_object::mlir_convolution_add_clip<float_type(64x512x14x14:0x1x0x0, 64x512x14x14, 512x1x3x3, 64x512x14x14)>: 1.51298ms / 5 = 0.302596ms, 15%
old:: gpu::code_object::mlir_convolution_add_clip<float_type(64x128x56x56:0x1x0x0, 64x128x56x56, 128x1x3x3, 64x128x56x56)>: 1.0173ms / 1 = 1.0173ms, 12%
    new:: gpu::code_object::mlir_convolution_add_clip<float_type(64x128x56x56:0x1x0x0, 64x128x56x56, 128x1x3x3, 64x128x56x56)>: 1.19929ms / 1 = 1.19929ms, 12%
old:: gpu::code_object::mlir_convolution_add_clip<float_type(64x32x112x112:0x1x0x0, 64x32x112x112, 32x1x3x3, 64x32x112x112)>: 0.907552ms / 1 = 0.907552ms, 10%
    new:: gpu::code_object::mlir_convolution_add_clip<float_type(64x32x112x112:0x1x0x0, 64x32x112x112, 32x1x3x3, 64x32x112x112)>: 1.14789ms / 1 = 1.14789ms, 12%
```

So the second one from above has the largest gap, however, I cant reproduce this gap.

here are the numbers that I see : 

```mlir
// python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512'
// python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='/var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir'

// on develop

// mkarunar@x1001c3s0b1n0:~/work/rocMLIR/build$ python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512'
// Tuning: conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512
// /var/mkarunar/work/rocMLIR/build/bin/rocmlir-gen --operation conv2d -t f32 --arch gfx90a:sramecc+:xnack- --num_cu 110 --fil_layout gkcyx --in_layout ngchw --out_layout ngkhw --batchsize 64 --in_channels 1 --in_h 14 --in_w 14 --out_channels 1 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 1 --padding_w 1 --kernel-repeats 1 --perf_config= 
// /var/mkarunar/work/rocMLIR/build/bin/rocmlir-tuning-driver
// Tuned : conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512 : 16,32,8,16,16,4,1,1 with 0.027138461538461542 TFlops
// Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = 'conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512', perfConfig = 16,32,8,16,16,4,1,1

// python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='/var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir'
// /var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir
// conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512
// /var/mkarunar/work/rocMLIR/build/bin/rocmlir-tuning-driver
// Tuned : /var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir : 32,64,4,32,64,4,1,1 with 0.0007818255476954719 TFlops
// Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '/var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir', perfConfig = 32,64,4,32,64,4,1,1

// on rocm-rel-6.1

// mkarunar@x1001c3s0b1n0:~/work/rocMLIR/build$ python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512'
// Tuning: conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512
// /var/mkarunar/work/rocMLIR/build/bin/rocmlir-gen --operation conv2d -t f32 --arch gfx90a:sramecc+:xnack- --num_cu 110 --fil_layout gkcyx --in_layout ngchw --out_layout ngkhw --batchsize 64 --in_channels 1 --in_h 14 --in_w 14 --out_channels 1 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 1 --padding_w 1 --kernel-repeats 1 --perf_config= 
// /var/mkarunar/work/rocMLIR/build/bin/rocmlir-tuning-driver
// Tuned : conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512 : 64,64,4,32,32,8,1,1 with 0.0252 TFlops
// Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = 'conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512', perfConfig = 64,64,4,32,32,8,1,1

// python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='/var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir'
// /var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir
// conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512
// /var/mkarunar/work/rocMLIR/build/bin/rocmlir-tuning-driver
// Tuned : /var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir : 32,64,4,32,64,4,1,1 with 0.0007835619670947838 TFlops
// Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '/var/mkarunar/work/rocMLIR/build/1429_perf/conv2.mlir', perfConfig = 32,64,4,32,64,4,1,1

#map = affine_map<(d0, d1, d2, d3) -> (d1, d0, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (0, d1, 0, 0)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1 + d2, d3, d4)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d0 + d1, d2, d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#transform_map = #rock.transform_map<#map by [<PassThrough ["dim1", "dim0", "dim2", "dim3"] at [0, 1, 2, 3] -> ["dim1", "dim0", "dim2", "dim3"] at [1, 0, 2, 3]>] bounds = [1, 512, 1, 1] -> [512, 1, 1, 1]>
#transform_map1 = #rock.transform_map<#map1 by [<Broadcast{1} ["dim0"] at [0] -> ["dim0"] at [0]>, <PassThrough ["dim1"] at [1] -> ["dim1"] at [1]>, <Broadcast{1} ["dim2"] at [2] -> ["dim2"] at [2]>, <Broadcast{1} ["dim3"] at [3] -> ["dim3"] at [3]>] bounds = [64, 512, 14, 14] -> [1, 512, 1, 1]>
#transform_map2 = #rock.transform_map<#map2 by [<PassThrough ["n", "h", "w"] at [0, 3, 4] -> ["n", "h", "w"] at [0, 2, 3]>, <Unmerge{512, 1} ["g", "c"] at [1, 2] -> ["c"] at [1]>] bounds = [64, 512, 1, 14, 14] -> [64, 512, 14, 14]>
#transform_map3 = #rock.transform_map<#map3 by [<PassThrough ["c", "y", "x"] at [2, 3, 4] -> ["c", "y", "x"] at [1, 2, 3]>, <Unmerge{512, 1} ["g", "k"] at [0, 1] -> ["k"] at [0]>] bounds = [512, 1, 1, 3, 3] -> [512, 1, 3, 3]>
#transform_map4 = #rock.transform_map<#map2 by [<PassThrough ["n", "h", "w"] at [0, 3, 4] -> ["n", "h", "w"] at [0, 2, 3]>, <Unmerge{512, 1} ["g", "k"] at [1, 2] -> ["k"] at [1]>] bounds = [64, 512, 1, 14, 14] -> [64, 512, 14, 14]>
module attributes {mhal.arch = "gfx90a:sramecc+:xnack-"} {
  func.func @mlir_convolution_add_clip(%arg0: memref<512x1x1x1xf32>, %arg1: memref<64x512x14x14xf32>, %arg2: memref<512x1x3x3xf32>, %arg3: memref<64x512x14x14xf32>) attributes {arch = "gfx90a:sramecc+:xnack-", kernel = "mixr", num_cu = 110 : i64} {
    %cst = arith.constant 6.000000e+00 : f32
    %cst_0 = arith.constant 0.000000e+00 : f32
    %0 = rock.transform %arg0 by #transform_map : memref<512x1x1x1xf32> to memref<1x512x1x1xf32>
    %1 = rock.transform %0 by #transform_map1 : memref<1x512x1x1xf32> to memref<64x512x14x14xf32>
    %alloc = memref.alloc() {alignment = 64 : i64} : memref<64x512x14x14xf32>
    %2 = rock.transform %arg1 by #transform_map2 : memref<64x512x14x14xf32> to memref<64x512x1x14x14xf32>
    %3 = rock.transform %arg2 by #transform_map3 : memref<512x1x3x3xf32> to memref<512x1x1x3x3xf32>
    %4 = rock.transform %alloc by #transform_map4 : memref<64x512x14x14xf32> to memref<64x512x1x14x14xf32>
    rock.conv2d(%3, %2, %4) features =  mfma|dot|atomic_add {arch = "gfx90a:sramecc+:xnack-", dilations = [1 : i32, 1 : i32], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], numCU = 110 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [1 : i32, 1 : i32, 1 : i32, 1 : i32], strides = [1 : i32, 1 : i32]} : memref<512x1x1x3x3xf32>, memref<64x512x1x14x14xf32>, memref<64x512x1x14x14xf32>
    %alloc_1 = memref.alloc() {alignment = 64 : i64} : memref<64x512x14x14xf32>
    linalg.generic {indexing_maps = [#map4, #map4, #map4], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%alloc, %1 : memref<64x512x14x14xf32>, memref<64x512x14x14xf32>) outs(%alloc_1 : memref<64x512x14x14xf32>) {
    ^bb0(%in: f32, %in_2: f32, %out: f32):
      %5 = arith.addf %in, %in_2 : f32
      %6 = arith.maxf %5, %cst_0 : f32
      %7 = arith.minf %6, %cst : f32
      linalg.yield %7 : f32
    }
    memref.copy %alloc_1, %arg3 : memref<64x512x14x14xf32> to memref<64x512x14x14xf32>
    return
  }
}
```

**Comment by manupak** [comment] 2024-03-04 15:57
At this point, can you share the paths to models ?

**Comment by causten** [comment] 2024-03-04 17:19
The comparison should be rocm 6.0.2, MIGX develop, and then toggle the mlir commit.  
Path to Models is on the NAS, migraphx/models/slim

**Comment by manupak** [comment] 2024-03-04 17:24
Why should MIGX commit needs changing?

**Comment by manupak** [comment] 2024-03-04 18:43
I mean I should be only using migraphx latest develop right ? coz the perf drop you are reporting is only relevant to mlir commit change (and not migraphx commit ?).

**Comment by causten** [comment] 2024-03-04 19:59
> I mean I should be only using migraphx latest develop right ? coz the perf drop you are reporting is only relevant to mlir commit change (and not migraphx commit ?).

the before and after commit was from the 6.1 commit vs the mlir mainline.

**Comment by manupak** [comment] 2024-03-05 12:26
Ok I cant reproduce this at model (mobilenet) level either : 
MIGX commit : effedcd204d57f9e92f47036f7b0a6513b6b3304
before MLIR commit(rel-6.1) : 833938473ae042ae4b610b25ae3810d03c1b9921
after MLIR commit : 1326212996682a1f61c01d2797107ce2dea99973

[develop_perf.log](https://github.com/ROCm/rocMLIR/files/14495177/develop_perf.log)
[rel6_1_perf.log](https://github.com/ROCm/rocMLIR/files/14495179/rel6_1_perf.log)

**Comment by manupak** [comment] 2024-03-05 12:28
Seems like chasing a ghost to me... @causten can you double check with above commits ?

**Comment by manupak** [comment] 2024-03-05 12:48
ok, I reproduced it : its between https://github.com/ROCm/rocMLIR/commit/bf2911e5245d6452d194ee5dc41c9c2b2869e5c0 & https://github.com/ROCm/rocMLIR/commit/833938473ae042ae4b610b25ae3810d03c1b9921

**Comment by manupak** [comment] 2024-03-05 13:15
ok found the culprit : 96f6d5a087ffe44e37908cb91199cfcfb4e75dd7

before: 

```
python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='/var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir'
Tuning:conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512 from /var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir
Tuned : /var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir : 4,64,2,4,64,8,1,1 with 0.0010634513941220798 TFlops
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '/var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir', perfConfig = 4,64,2,4,64,8,1,1
```

after:

```
mkarunar@x1001c3s0b1n0:~/work/rocMLIR/build$ python3 ./bin/tuningRunner.py --op conv --tuning-space=quick --verify-mode=none --config='/var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir'
Tuning:conv -F 1 -f GNCHW -I NGCHW -O NGCHW -n 64 -c 1 -H 14 -W 14 -k 1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 512 from /var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir
Tuned : /var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir : 32,64,4,32,64,4,1,1 with 0.0007844330724254016 TFlops
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '/var/mkarunar/work/rocMLIR/1429_perf/conv2.mlir', perfConfig = 32,64,4,32,64,4,1,1
```

**Comment by manupak** [comment] 2024-03-05 13:15
@yiqian1 can you take a look ?

**Comment by manupak** [comment] 2024-03-05 13:25
[d1bc027_perf.log](https://github.com/ROCm/rocMLIR/files/14495849/d1bc027_perf.log)

**Closed as completed** 2024-03-08 15:20 UTC
